# Site settings
title: Adrian's Portfolio
email: adrian.m.ryan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first Jekyll site, made following the tutorial at http://www.taniarascia.com/make-a-static-website-with-jekyll/
baseurl: "/page1"
url: "http://1point618.github.io"
twitter_username: AdrianMRyan
github_username:  1point618

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - home