# Site settings
title: Super GitHub User
email: hello@wheelhouse.io
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: "/portfolio"
url: "http://localhost:4000"
twitter_username: WheelhouseIO
github_username:  wheelhouseio
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index